---
# FILE:            group_vars/functions.yml
# LICENSE:         Public Domain

faas_base: "https://osm-faas.etica.ai"
faas_function_base: "https://osm-faas.etica.ai/function"

faas_index_template: "{{ playbook_dir }}/templates/faas/index.jsonld.j2"
faas_index_destiny: "/var/www/html/index.jsonld"
faas_jsonschema_template: "{{ playbook_dir }}/templates/faas/schema.json.j2"
faas_jsonschema_destiny: "/var/www/html/schema.json"
faas_jsonldcontext_template: "{{ playbook_dir }}/templates/faas/context.jsonld.j2"
faas_jsonldcontext_destiny: "/var/www/html/context.jsonld"

# @see http://www.hydra-cg.com/spec/latest/core/
# This list only contains a short list of apps, likely the most common ones used
faas_functions:

  - id: api-proxy
    entrypoint: "{{ faas_base }}/api-proxy"
    public: true

  - id: api-rdf
    entrypoint: "{{ faas_base }}/api-rdf"
    public: true

  - id: wiki-as-base
    entrypoint: "{{ faas_base }}/wiki-as-base"
    public: true

  # No alias, use /function/
  - id: nodeinfo
    entrypoint: "{{ faas_base }}/function/nodeinfo"
    public: true

  # No alias, use /function/
  - id: cows
    entrypoint: "{{ faas_base }}/function/cows"
    public: true
