---
# FILE:            inventories/osmbr/host_vars/osmbr_bravo.yml
# LICENSE:         Public Domain

# osm-faas.etica.ai CNAME osmbra-bravo.etica.ai (cloudflare auto HTTPS)


ansible_host: osmbra-bravo.etica.ai
# ansible_python_interpreter: "/usr/bin/python3"
node_ipv4: 167.86.127.220
node_iata: MUC # Munich, Germany
node_provider: Contabo
node_base: "{{ playbook_dir }}/files/osmbr_bravo"
node_port_ssh: 65432

ansible_user: root
# ansible_user: ansible
# ansible_become: yes
# ansible_become_user: root