---
# FILE:            playbooks/infra-munin-full.yml
# LICENSE:         Public Domain
#
# DESCRIPTION:     Munin full configure both an node to be accessed by other
#                  places AND to show web interface.
#
# SEE:             https://github.com/geerlingguy/ansible-role-munin
#                  http://guide.munin-monitoring.org/en/latest/tutorial/troubleshooting.html (debug)
# LOGS:            /var/log/munin/munin-node.log
#                  /var/log/munin/munin-update.log
# USAGE:
# To run this playbook alone, use:
#     ansible-playbook -i inventories/osmbr playbooks/infra-munin-full.yml
#
# To run manually (@see https://gist.github.com/viegelinsch/5bd149a63e9a4ebb2373)
#    su - munin --shell=/bin/bash -c /usr/share/munin/munin-update
#    su - munin --shell=/bin/bash -c "/usr/share/munin/munin-update -debug"
#

- name: "infra-munin-full.yml: geerlingguy.munin"
  hosts: munin_full
  # remote_user: root
  # gather_facts: false
  debugger: on_failed
  # vars:
  #   # munin_setupfcgi_enabled: false
  #   munin_setupfcgi_packages:
  #     - spawn-fcgi
  roles:
    - role: geerlingguy.munin

  # tasks:
  #   ### Allow dynamic zoom _____________________________________________________
  #   # @see http://munin-monitoring.org/wiki/MuninConfigurationMasterCGI
  #   - name: "infra-munin-full.yml: | munin_setupfcgi_packages install"
  #     package:
  #       name: "{{ (item.name is defined) | ternary(item.name, item) }}"
  #       state: "{{ (item.name is defined and item.state is defined) | ternary(item.state, omit) }}"
  #       use: "{{ (item.name is defined and item.use is defined) | ternary(item.use, omit) }}"
  #     with_items: "{{ munin_setupfcgi_packages }}"
  #     when:
  #       - "(munin_setupfcgi_enabled is defined) and (munin_setupfcgi_enabled|bool)"

  #    ## Run this command when you need to see the graphs
  #    # sudo spawn-fcgi -s /var/run/munin/fastcgi-graph.sock -U www-data -u www-data -g www-data /usr/lib/munin/cgi/munin-cgi-graph
  #    # > spawn-fcgi: child spawned successfully: PID: 556043

  #   - name: "infra-munin-full.yml: | munin_setupfcgi_packages alert about the need to spaw manually"
  #     debug:
  #       msg: 
  #         information: |
  #           munin_setupfcgi_enabled is required, but this script does not deploy systemd services.
  #           When need to inspect these graphs, please run the adhoc_spawn_fcgi_command
  #         adhoc_spawn_fcgi_command: "sudo spawn-fcgi -s /var/run/munin/fastcgi-graph.sock -U www-data -u www-data -g www-data /usr/lib/munin/cgi/munin-cgi-graph"
  #         todo_systemd: "https://redmine.lighttpd.net/projects/spawn-fcgi/wiki/Systemd"
  #     when:
  #       - "(munin_setupfcgi_enabled is defined) and (munin_setupfcgi_enabled|bool)"

#  geerlingguy.munin-node is need if node port is customized. Thats why we're
#  calling even on a node with the web interface
- name: "infra-munin-full.yml: geerlingguy.munin-node"
  hosts: munin_full
  # remote_user: root
  # gather_facts: true
  debugger: on_failed
  roles:
    - role: geerlingguy.munin-node