---
# FILE:            infra-openfaasd.yml
# LICENSE:         Public Domain
# DESCRIPTION:     Based on cloud-config.txt from faasd from
#                  github.com/openfaas/faasd/blob/master/cloud-config.txt

# ansible-playbook -i inventories/osmbr playbooks/infra-openfaasd.yml -vv

- name: "infra-openfaasd.yml"
  hosts: "openfaasd"
  become: true
  become_user: root
  debugger: on_failed
  gather_facts: false

  tasks:
    # - name: "infra-openfaasd.yml | ping all"
    #   ping:
    #     data: pong

    # - name: "infra-openfaasd.yml | install git"
    #   ansible.builtin.package:
    #     name:
    #       - git
    #     state: latest

    - name: "infra-openfaasd.yml | faasd installed ?"
      # command: command -v faasd >/dev/null 2>&1
      shell: command -v faasd >/dev/null 2>&1
      register: installed
      # no_log: true
      ignore_errors: true
      changed_when: false

    - name: "infra-openfaasd.yml | download /root/faasd-hack-install.sh"
      get_url:
        url: https://raw.githubusercontent.com/openfaas/faasd/master/hack/install.sh
        dest: /root/faasd-hack-install.sh
        mode: "u+rwx"
      when: installed.rc != 0
      register: download

    - name: "infra-openfaasd.yml | run /root/faasd-hack-install.sh"
      shell: /root/faasd-hack-install.sh
      when: download.changed

    - name: "infra-openfaasd.yml | faas-cli installed ?"
      # command: command -v faas-cli >/dev/null 2>&1
      shell: command -v faas-cli >/dev/null 2>&1
      register: installed_faascli
      # no_log: true
      ignore_errors: true
      changed_when: false

    - name: "infra-openfaasd.yml | download /root/faas-cli-install.sh"
      get_url:
        url: https://cli.openfaas.com
        dest: /root/faas-cli-install.sh
        mode: "u+rwx"
      when: installed_faascli.rc != 0
      register: download_faascli

    - name: "infra-openfaasd.yml | run /root/faasd-hack-install.sh"
      shell: /root/faas-cli-install.sh
      when: download_faascli.changed

### Reference: https://github.com/openfaas/faasd/blob/master/cloud-config.txt
# #cloud-config
# ssh_authorized_keys:
# ## Note: Replace with your own public key
#   - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8Q/aUYUr3P1XKVucnO9mlWxOjJm+K01lHJR90MkHC9zbfTqlp8P7C3J26zKAuzHXOeF+VFxETRr6YedQKW9zp5oP7sN+F2gr/pO7GV3VmOqHMV7uKfyUQfq7H1aVzLfCcI7FwN2Zekv3yB7kj35pbsMa1Za58aF6oHRctZU6UWgXXbRxP+B04DoVU7jTstQ4GMoOCaqYhgPHyjEAS3DW0kkPW6HzsvJHkxvVcVlZ/wNJa1Ie/yGpzOzWIN0Ol0t2QT/RSWOhfzO1A2P0XbPuZ04NmriBonO9zR7T1fMNmmtTuK7WazKjQT3inmYRAqU6pe8wfX8WIWNV7OowUjUsv alex@alexr.local

# package_update: true

# packages:
#  - runc
#  - git

# runcmd:
# - curl -sfL https://raw.githubusercontent.com/openfaas/faasd/master/hack/install.sh | bash -s -
# - systemctl status -l containerd --no-pager
# - journalctl -u faasd-provider --no-pager
# - systemctl status -l faasd-provider --no-pager
# - systemctl status -l faasd --no-pager
# - curl -sSLf https://cli.openfaas.com | sh
# - sleep 60 && journalctl -u faasd --no-pager
# - cat /var/lib/faasd/secrets/basic-auth-password | /usr/local/bin/faas-cli login --password-stdin
